# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a740b7cdbde69bf2338ddcf3b5500d96cd431189cb68c740018d75353f80b84eedfd06c26fcc5a498dac2255b8cd2282185b7e114c9855ba6f04e15a05791106

test:
  secret_key_base: d550fc470017a3878cd600024a7a194d7f67734737fc6f013fad5098a351542f63f7b3e0b01d02674940c12d32901152bf4adce21395e6459e470ba5b292e85c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
